### ISSUE TITLE
Release 1.1 Checklist

### ISSUE THREAD

**Issue by habmin** [hobg0blin/dataville#117]
- [ ] [Mobile-playable](https://github.com/hobg0blin/dataville/issues/116)
- [ ] [Job offer buttons](https://github.com/hobg0blin/dataville/issues/52)
- [ ] [Make news intro easier to understand who's talking](https://github.com/hobg0blin/dataville/issues/80)
- [ ] [Loading Splash should advise people that web/mobile is experimental](https://github.com/hobg0blin/dataville/issues/115)
- [ ] [credits in "about" screen](https://github.com/hobg0blin/dataville/issues/24)
- [ ] [Upgrade the sticky notes](https://github.com/hobg0blin/dataville/issues/107)
- [ ] [Bug with the click to advance](https://github.com/hobg0blin/dataville/issues/112)
