### ISSUE TITLE
final build checklist

### ISSUE THREAD

**Issue by hobg0blin** [hobg0blin/dataville#37]
- [x] Remove old builds
- [x] Clean all those print() calls
- [x] Remove unused assets (images, audio, fonts)
- [x] Compress Audio
- [x] Maybe compressing some PNGs
- [x] Goal >1gb
   - [ ] if not, we can talk to itch about getting 4gb

Test mac/pc/maybe linux builds?

**Comment by habmin** [comment]
Goal >1gb, if not, we can talk to itch about getting 4gb

- [ ] Remove old builds
- [ ] Remove unused assets (images, audio, fonts)
- [ ] Compress Audio
- [ ] Maybe compressing some PNGs
